### ISSUE TITLE
question - impact of RDF

### ISSUE THREAD

**Issue by alenhorvat** [transmute-industries/vc-jwt-sd#6]
Hi.
Thank you for the great work.

Did you check, or do you know, the impact of RDF/normalisation processing? 
Should we expect any difference if we strip that away (for pedagogical purposes)?

**Comment by OR13** [comment]
sorry, just seeing this comment... I suggest you not attempt any RDF operations at the crypto sign / verify layer, it leads to lots of possible denial of service attack vectors.
